### ISSUE TITLE
Laser Detector flickering is not delaying correctly

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#3]
After playing the sequence there is a small delay which causes the last state to be held for a too long period. Printing in _on_FlickerTimer_timeout shows this.

**Comment by kneghtmare** [comment]
Fixed, check

**Comment by themangomago** [comment]
Still not correct. 
![GIF](https://user-images.githubusercontent.com/29095714/112639579-b6bfb400-8e40-11eb-84e3-20f6fa31c93b.gif)
Flicker sequence is: 1100 so it shall be equaly distributed.

**Comment by themangomago** [comment]
fixed now
